apiVersion: batch/v1
kind: Job
metadata:
  name: create-site
spec:
  template:
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: create-site
        image: frappe/erpnext:v15.55.0
        command:
        - bash
        - -c
        args:
        - |
          wait-for-it -t 120 db:3306;
          wait-for-it -t 120 redis-cache:6379;
          wait-for-it -t 120 redis-queue:6379;
          export start=`date +%s`;
          until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
            [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
            [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
          do
            echo "Waiting for sites/common_site_config.json to be created";
            sleep 5;
            if (( `date +%s`-start > 120 )); then
              echo "could not find sites/common_site_config.json with required keys";
              exit 1
            fi
          done;
          echo "sites/common_site_config.json found";
          bench new-site --mariadb-user-host-login-scope='%' --admin-password=admin --db-root-username=root --db-root-password=admin --install-app erpnext --set-default frontend;
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        volumeMounts:
        - name: sites
          mountPath: /home/frappe/frappe-bench/sites
        - name: logs
          mountPath: /home/frappe/frappe-bench/logs
      volumes:
      - name: sites
        hostPath:
          path: "/mnt/data/sites"
          type: DirectoryOrCreate
      - name: logs
        hostPath:
          path: "/mnt/data/logs"
          type: DirectoryOrCreate
      restartPolicy: OnFailure