apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f pwd.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  containers:
    - args:
        - nginx-entrypoint.sh
      env:
        - name: BACKEND
          value: backend:8000
        - name: CLIENT_MAX_BODY_SIZE
          value: 50m
        - name: FRAPPE_SITE_NAME_HEADER
          value: frontend
        - name: PROXY_READ_TIMEOUT
          value: "120"
        - name: SOCKETIO
          value: websocket:9000
        - name: UPSTREAM_REAL_IP_ADDRESS
          value: 127.0.0.1
        - name: UPSTREAM_REAL_IP_HEADER
          value: X-Forwarded-For
        - name: UPSTREAM_REAL_IP_RECURSIVE
          value: "off"
      image: frappe/erpnext:v15.55.0
      name: frontend
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: /home/frappe/frappe-bench/sites
          name: sites
        - mountPath: /home/frappe/frappe-bench/logs
          name: logs
      # resources:
      #     requests:
      #       memory: "512Mi"     
      #       cpu: "500m"        
      #     limits:
      #       memory: "1Gi"       
      #       cpu: "1"
  restartPolicy: OnFailure
  volumes:
    - name: sites
      persistentVolumeClaim:
        claimName: sites
    - name: logs
      persistentVolumeClaim:
        claimName: logs
