apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f pwd.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: scheduler
  name: scheduler
spec:
  containers:
    - args:
        - bench
        - schedule
      image: frappe/erpnext:v15.55.0
      name: scheduler
      volumeMounts:
        - mountPath: /home/frappe/frappe-bench/sites
          name: sites
        - mountPath: /home/frappe/frappe-bench/logs
          name: logs
      # resources:
      #     requests:
      #       memory: "512Mi"     
      #       cpu: "500m"        
      #     limits:
      #       memory: "1Gi"       
      #       cpu: "1"
  restartPolicy: OnFailure
  volumes:
    - name: sites
      persistentVolumeClaim:
        claimName: sites
    - name: logs
      persistentVolumeClaim:
        claimName: logs
