apiVersion: batch/v1
kind: Job
metadata:
  name: configurator
  namespace: erpnext
spec:
  template:
    spec:
      containers:
      - name: configurator
        image: frappe/erpnext:v15.55.0
        envFrom:
        - configMapRef:
            name: erpnext-config
        command:
        - bash
        - -c
        - |
          ls -1 apps > sites/apps.txt;
          bench set-config -g db_host $DB_HOST;
          bench set-config -gp db_port $DB_PORT;
          bench set-config -g redis_cache "redis://$REDIS_CACHE";
          bench set-config -g redis_queue "redis://$REDIS_QUEUE";
          bench set-config -g redis_socketio "redis://$REDIS_QUEUE";
          bench set-config -gp socketio_port $SOCKETIO_PORT;
        volumeMounts:
        - name: sites
          mountPath: /home/frappe/frappe-bench/sites
      volumes:
      - name: sites
        persistentVolumeClaim:
          claimName: sites-pvc
      restartPolicy: OnFailure