apiVersion: batch/v1
kind: Job
metadata:
  name: create-site
  namespace: erpnext
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-configurator
        image: busybox
        command: ['sh', '-c', 'until [ -f /sites/common_site_config.json ]; do echo waiting for configurator; sleep 5; done;']
        volumeMounts:
        - name: sites
          mountPath: /sites
      containers:
      - name: create-site
        image: frappe/erpnext:v15.55.0
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: erpnext-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: erpnext-config
              key: DB_PORT
        - name: REDIS_CACHE
          valueFrom:
            configMapKeyRef:
              name: erpnext-config
              key: REDIS_CACHE
        - name: REDIS_QUEUE
          valueFrom:
            configMapKeyRef:
              name: erpnext-config
              key: REDIS_QUEUE
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: erpnext-secrets
              key: mysql_root_password
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: erpnext-secrets
              key: mariadb_root_password
        command:
        - bash
        - -c
        - |
          wait-for-it -t 120 db:3306;
          wait-for-it -t 120 redis-cache:6379;
          wait-for-it -t 120 redis-queue:6379;
          export start=`date +%s`;
          until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
            [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
            [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]]; do
            echo "Waiting for sites/common_site_config.json to be created";
            sleep 5;
            if (( `date +%s`-start > 120 )); then
              echo "could not find sites/common_site_config.json with required keys";
              exit 1
            fi
          done;
          echo "sites/common_site_config.json found";
          bench new-site --mariadb-user-host-login-scope='%' --admin-password=admin --db-root-username=root --db-root-password=admin --install-app erpnext --set-default frontend;
        volumeMounts:
        - name: sites
          mountPath: /home/frappe/frappe-bench/sites
        - name: logs
          mountPath: /home/frappe/frappe-bench/logs
      volumes:
      - name: sites
        persistentVolumeClaim:
          claimName: sites-pvc
      - name: logs
        persistentVolumeClaim:
          claimName: logs-pvc
      restartPolicy: OnFailure