apiVersion: v1
kind: ConfigMap
metadata:
  name: erpnext-config
  namespace: erpnext
data:
  DB_HOST: db
  DB_PORT: "3306"
  REDIS_CACHE: redis-cache:6379
  REDIS_QUEUE: redis-queue:6379
  SOCKETIO_PORT: "9000"
  FRAPPE_SITE_NAME_HEADER: frontend
  UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
  UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
  UPSTREAM_REAL_IP_RECURSIVE: "off"
  PROXY_READ_TIMEOUT: "120"
  CLIENT_MAX_BODY_SIZE: "50m"
  BACKEND: backend:8000
  SOCKETIO: websocket:9000