apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: erpnext
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frappe/erpnext:v15.55.0
        command: ["nginx-entrypoint.sh"]
        envFrom:
        - configMapRef:
            name: erpnext-config
        volumeMounts:
        - name: sites
          mountPath: /home/frappe/frappe-bench/sites
        - name: logs
          mountPath: /home/frappe/frappe-bench/logs
      volumes:
      - name: sites
        persistentVolumeClaim:
          claimName: sites-pvc
      - name: logs
        persistentVolumeClaim:
          claimName: logs-pvc