apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  namespace: erpnext
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard