apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-queue-data-pvc
  namespace: erpnext
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard